package com.finance.finlog.global.scheduler;

import com.finance.finlog.domain.saving.entity.GoalStatus;
import com.finance.finlog.domain.saving.entity.SavingGoal;
import com.finance.finlog.domain.saving.repository.SavingGoalRepository;
import com.finance.finlog.domain.subscription.entity.Subscription;
import com.finance.finlog.domain.subscription.repository.SubscriptionRepository;
import com.finance.finlog.domain.transaction.entity.Transaction;
import com.finance.finlog.domain.transaction.entity.TransactionType;
import com.finance.finlog.domain.transaction.repository.TransactionRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class SchedulerService {
    private final SubscriptionRepository subscriptionRepository;
    private final TransactionRepository transactionRepository;
    private final SavingGoalRepository savingGoalRepository;

    // 매일 자정 - 구독 자동 처리
    @Scheduled(cron = "0 0 0 * * *") // 매일 0초 0분 0시
    @Transactional
    public void processSubscriptions() {
        LocalDate today = LocalDate.now();
        List<Subscription> subscriptions = subscriptionRepository.findAllByNextBillingDateAndIsActiveTrue(today);

        log.info("[Scheduler] 구독 자동 처리 시작 - 대상: {}건", subscriptions.size());

        for (Subscription subscription : subscriptions) {
            // 거래 내역 자동 생성
            Transaction transaction = Transaction.builder()
                    .user(subscription.getUser())
                    .category(subscription.getCategory())
                    .subscription(subscription)
                    .type(TransactionType.EXPENSE)
                    .amount(subscription.getAmount())
                    .description(subscription.getName() + " 정기 결제")
                    .transactionDate(today)
                    .isAutoGenerated(true)
                    .build();

            transactionRepository.save(transaction);

            // 다음 결제일 갱심
            LocalDate nextMonth = today.plusMonths(1);
            LocalDate nextBillingDate = nextMonth.withDayOfMonth(Math.min(subscription.getBillingDay(), nextMonth.lengthOfMonth()));
            subscription.updateNextBillingDate(nextBillingDate);

            log.info("[Scheduler] 구독 처리 완료 - {}, 다음 결제일: {}",
                    subscription.getName(), nextBillingDate);
        }
    }

    // 매일 자정 - 만료된 목표 처리
    @Scheduled(cron = "0 0 0 * * *") // 매일 0초 0분 0시
    @Transactional
    public void processExpiredGoals(){
        LocalDate today = LocalDate.now();
        List<SavingGoal> expiredGoals = savingGoalRepository
                .findAllByStatusAndDeadlineBefore(GoalStatus.IN_PROGRESS, today);

        log.info("[Scheduler] 만료 목표 처리 시작 - 대상: {}건", expiredGoals.size());

        for (SavingGoal goal : expiredGoals) {
            goal.expire();
            log.info("[Scheduler] 목표 만료 처리 - {}", goal.getName());
        }
    }
}
