package com.finance.finlog.domain.transaction.entity;

import com.finance.finlog.domain.category.entity.Category;
import com.finance.finlog.domain.subscription.entity.Subscription;
import com.finance.finlog.domain.user.entity.User;
import com.finance.finlog.global.common.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Table(name = "transactions")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Builder
@AllArgsConstructor
// 수입과 지출 내역
// 누가 언제 얼마를 어떤 카테고리에서 수입/지출 했는지
public class Transaction extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY) // 한명의 유저는 여러 거래내역을 가질 수 있다.
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY) // 한 카테고리에 여러 거래내역 존재가능
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    @ManyToOne(fetch = FetchType.LAZY) // 한 구독에 여러 거래내역 존재가능
    @JoinColumn(name = "subscription_id") // 식사나데이트로 수입/지출한다면 해당 컬럼은 null 가능
    private Subscription subscription;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;

    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal amount; // 부동소수점 오류 때문에 BigDecimal 사용

    private String description;

    @Column(nullable = false)
    private LocalDate transactionDate;

    @Column(nullable = false)
    private boolean isAutoGenerated;

    // 자동 생성된 거래 말고, 유저가 직접 등록한 거래는 수정가능하게 하는 메서드
    public void update(TransactionType type, BigDecimal amount,
                       String description, LocalDate transactionDate,
                       Category category) {
        this.type = type;
        this.amount = amount;
        this.description = description;
        this.transactionDate = transactionDate;
        this.category = category;
    }
}
