package com.finance.finlog.domain.transaction.dto;

import com.finance.finlog.domain.transaction.entity.Transaction;
import com.finance.finlog.domain.transaction.entity.TransactionType;
import lombok.Getter;

import java.math.BigDecimal;
import java.time.LocalDate;

@Getter
public class TransactionResponse {

    private final Long id;
    private final TransactionType type;
    private final BigDecimal amount;
    private final String description;
    private final LocalDate transactionDate;
    private final String categoryName;
    private final boolean isAutoGenerated;

    private TransactionResponse(Transaction transaction) {
        this.id = transaction.getId();
        this.type = transaction.getType();
        this.amount = transaction.getAmount();
        this.description = transaction.getDescription();
        this.transactionDate = transaction.getTransactionDate();
        this.categoryName = transaction.getCategory().getName();
        this.isAutoGenerated = transaction.isAutoGenerated();
    }

    public static TransactionResponse from(Transaction transaction) {
        return new TransactionResponse(transaction);
    }
}