package com.finance.finlog.domain.transaction.service;

import com.finance.finlog.domain.category.entity.Category;
import com.finance.finlog.domain.category.repository.CategoryRepository;
import com.finance.finlog.domain.transaction.dto.MonthlyStatResponse;
import com.finance.finlog.domain.transaction.dto.TransactionRequest;
import com.finance.finlog.domain.transaction.dto.TransactionResponse;
import com.finance.finlog.domain.transaction.entity.Transaction;
import com.finance.finlog.domain.transaction.entity.TransactionType;
import com.finance.finlog.domain.transaction.repository.TransactionRepository;
import com.finance.finlog.domain.user.entity.User;
import com.finance.finlog.domain.user.repository.UserRepository;
import com.finance.finlog.global.common.BusinessException;
import com.finance.finlog.global.security.RedisService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class TransactionService {

    private final TransactionRepository transactionRepository;
    private final CategoryRepository categoryRepository;
    private final UserRepository userRepository;
    private final RedisService redisService;

    private final long STATS_CACHE_TTL = 1000 * 60 * 10; // 10분

    // 월별 거래 내역 조회
    public List<TransactionResponse> getTransactions(Long userId, int year, int month) {
        User user = getUser(userId);
        LocalDate start = LocalDate.of(year, month, 1);
        LocalDate end = start.withDayOfMonth(start.lengthOfMonth()); // 달마다 마지막 날이 다름

        return transactionRepository
                .findAllByUserAndTransactionDateBetweenOrderByTransactionDateDesc(
                        user, start, end)
                .stream()
                .map(TransactionResponse::from)
                .toList();
    }

    // 월별 통계 조회
    public MonthlyStatResponse getMonthlyStat(Long userId, int year, int month) {

        // 캐시 키 생성
        String cacheKey = "stats:" + userId + ":" + year + ":" + month;

        // 캐시에 있으면 바로 반환
        if(redisService.hasKey(cacheKey)){
            String cached = redisService.get(cacheKey);
            return parseCachedStat(cached, year, month);
        }

        // 없다면 DB 조회
        User user = getUser(userId);

        // TransactionType Enum으로 넘김(타입 안전)
        BigDecimal totalIncome = transactionRepository
                .sumAmountByUserAndTypeAndYearMonth(
                        user, TransactionType.INCOME, year, month);

        BigDecimal totalExpense = transactionRepository
                .sumAmountByUserAndTypeAndYearMonth(
                        user, TransactionType.EXPENSE, year, month);

        MonthlyStatResponse result = new MonthlyStatResponse(year, month, totalIncome, totalExpense);


        // Redis에 캐시 저장
        redisService.set(cacheKey, totalIncome + ":" + totalExpense, STATS_CACHE_TTL);

        return result;
    }

    // 거래 생성
    @Transactional
    public TransactionResponse createTransaction(Long userId, TransactionRequest request) {
        User user = getUser(userId);
        Category category = categoryRepository
                .findByIdAndUser(request.getCategoryId(), user)
                .orElseThrow(() -> BusinessException.notFound("카테고리를 찾을 수 없습니다"));

        Transaction transaction = Transaction.builder()
                .user(user)
                .category(category)
                .type(request.getType())
                .amount(request.getAmount())
                .description(request.getDescription())
                .transactionDate(request.getTransactionDate())
                .isAutoGenerated(false)
                .build();

        TransactionResponse response = TransactionResponse.from(transactionRepository.save(transaction));

        invalidateStatCache(userId, request.getTransactionDate()); // 캐시 무효화

        return response;
    }

    // 거래 수정
    @Transactional
    public TransactionResponse updateTransaction(Long userId, Long transactionId,
                                                 TransactionRequest request) {
        User user = getUser(userId);
        Transaction transaction = transactionRepository
                .findByIdAndUser(transactionId, user)
                .orElseThrow(() -> BusinessException.notFound("거래 내역을 찾을 수 없습니다"));

        if (transaction.isAutoGenerated()) {
            throw BusinessException.badRequest("자동 생성된 거래는 수정할 수 없습니다");
        }

        Category category = categoryRepository
                .findByIdAndUser(request.getCategoryId(), user)
                .orElseThrow(() -> BusinessException.notFound("카테고리를 찾을 수 없습니다"));

        transaction.update(request.getType(), request.getAmount(),
                request.getDescription(), request.getTransactionDate(), category);

        invalidateStatCache(userId, request.getTransactionDate()); // 캐시 무효화
        return TransactionResponse.from(transaction);
    }

    // 거래 삭제
    @Transactional
    public void deleteTransaction(Long userId, Long transactionId) {
        User user = getUser(userId);
        Transaction transaction = transactionRepository
                .findByIdAndUser(transactionId, user)
                .orElseThrow(() -> BusinessException.notFound("거래 내역을 찾을 수 없습니다"));

        if (transaction.isAutoGenerated()) {
            throw BusinessException.badRequest("자동 생성된 거래는 삭제할 수 없습니다");
        }
        invalidateStatCache(userId, transaction.getTransactionDate()); // 캐시 무효화
        transactionRepository.delete(transaction);
    }

    private User getUser(Long userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> BusinessException.notFound("유저를 찾을 수 없습니다"));
    }

    private void invalidateStatCache(Long userId, LocalDate date) {
        String cacheKey = "stats:" + userId+":"+date.getYear()+":"+date.getMonthValue();
        redisService.delete(cacheKey);
    }

    private MonthlyStatResponse parseCachedStat(String cached, int year, int month) {
        String[] parts = cached.split(":");
        return new MonthlyStatResponse(year, month, new BigDecimal(parts[0]), new BigDecimal(parts[1])
        );
    }
}